ARG DGRAPH_VERSION
FROM dgraph/dgraph:${DGRAPH_VERSION}-arm64
LABEL MAINTAINER="struct-ure.org <contact@struct-ure.org>"

EXPOSE 8080
EXPOSE 9080

ADD dgraph /dgraph
ADD run.sh /run.sh

RUN chmod +x /run.sh
CMD ["/run.sh"]
